#See results of SQL_VS_Pyspark with out execution from
https://k-lakshmikanth.github.io/Learn/SQL_VS_Pyspark.html

In [0]:
from pyspark import SparkFiles
spark.sparkContext.addFile('https://raw.githubusercontent.com/k-lakshmikanth/Databricks/main/emp.csv')
url = "file://"+SparkFiles.get("emp.csv")
df = spark.read.format("csv").option("inferSchema",True).option("header",'True').load(url)

In [0]:
#SELECT * FROM TABLE
display(df)

In [0]:
#SELECT COUNT(*) FROM  TABLE
df.count()

In [0]:
#DESCRIBE TABLE
df.printSchema()

In [0]:
#SELECT COLUMN1,COLUMN2 FROM TABLE
df.select(['empno','ename']).display()
#               | OR | 
df.select('empno','ename').display()

In [0]:
#SELECT * FROM TABLE WHERE COLUMN=NUMBER
display(df.filter('empno = 7369 '))

In [0]:
#SELECT *FROM TABLE WHERE COLUMN=STRING
display(df.filter('job = "MANAGER"'))

In [0]:
#SELECT *FROM TABLE WHERE COLUMN IN (NUMBERS)
display(df.filter('empno in (7369,7499,7566,7698)'))

In [0]:
#SELECT *FROM TABLE WHERE COLUMN IN (STRINGS)
display(df.filter('ename in ("JAMES","MILLER","FORD","MARTIN")'))

In [0]:
#SELECT *FROM TABLE WHERE COLUMN <> NUMBER
display(df.filter('mgr <> 7698'))

In [0]:
#SELECT *FROM TABLE WHERE COLUMN NOT IN (NUMBER)
display(df.filter('mgr not in (7698,7566,7902)'))

In [0]:
#SELECT *FROM TABLE WHERE COLUMN NOT IN (STRING)
display(df.filter('ename not in ("JAMES","MILLER","FORD","MARTIN")'))

In [0]:
#SELECT *FROM TABLE WHERE COLUMN LIKE '%XYZ'
display(df.filter('ename LIKE "%S" '))

In [0]:
#SELECT *FROM TABLE WHERE COLUMN LIKE 'XYZ%'
display(df.filter('ename LIKE "A%" '))

In [0]:
#SELECT *FROM TABLE WHERE COLUMN LIKE '%XYZ%'
display(df.filter('ename LIKE "%A%" '))

In [0]:
#SELECT *FROM TABLE WHERE COLUMN IS NULL
display(df.filter('comm is null'))

In [0]:
#SELECT *FROM TABLE WHERE COLUMN IS NOT NULL
display(df.filter('comm is not null'))

In [0]:
#SELECT * FROM TABLE WHERE COLUMN1 = NUMBER AND COLUMN2 = NUMBER 
display(df.filter('deptno = 30 and sal = 1500 '))

In [0]:
#SELECT * FROM TABLE WHERE COLUMN1 = STRING AND COLUMN2 = STRING 
display(df.filter('job = "SALESMAN" and sal = 1500'))

In [0]:
#SELECT LENGTH(COLUMN) FROM TABLE
from pyspark.sql.functions import length,col
#display(df.select(COLUMN).withColumn('Alias',length(col(COLUMN))))
display(df.select('ename').withColumn('length of ename',length(col('ename'))))

In [0]:
#SELECT UPPER(COLUMN) FROM TABLE
from pyspark.sql.functions import upper
#display(df.select(COLUMN).withColumn('Alias',upper(col(COLUMN))))
display(df.select('ename').withColumn('upper of ename',upper(col('ename'))))

In [0]:
#SELECT LOWER(COLUMN) FROM TABLE
from pyspark.sql.functions import lower
#display(df.select(COLUMN).withColumn('Alias',lower(col(COLUMN))))
display(df.select('ename').withColumn('lower of ename',lower(col("ename"))))

In [0]:
#TRIM
from pyspark.sql.functions import trim
#display(df.select(COLUMN).withColumn('Alias',trim(col(COLUMN))))
display(df.select('ename').withColumn('trim of ename',trim(col('ename'))))

In [0]:
#LTRIM
from pyspark.sql.functions import ltrim
#display(df.select(COLUMN).withColumn('Alias',ltrim(col(COLUMN))))
display(df.select('ename').withColumn('ltrim of ename',ltrim(col('ename'))))

In [0]:
#RTRIM
from pyspark.sql.functions import rtrim
#display(df.select(COLUMN).withColumn('Alias',rtrim(col(COLUMN))))
display(df.select('ename').withColumn('rtrim of ename',rtrim(col('ename'))))

In [0]:
#SELECT COLUMN1,SUM(COLUMN2) FROM TABLE GROUP BY COLUMN1
#display(df.select(COLUMN1,COLUMN2).groupby(COLUMN1).sum(COLUMN2))
display(df.select('deptno','sal').groupby('deptno').sum('sal'))

In [0]:
#SELECT COLUMN1,SUM(COLUMN2) FROM TABLE GROUP BY COLUMN1 HAVING SUM(COLUMN2)>100
display(df.select('deptno','sal').groupby('deptno').sum('sal').where(col("SUM(sal)")>=9400))

In [0]:
#Select job,len(job) as count from <Tablename> order by len(job) desc
from pyspark.sql.functions import length
df.select("job").withColumn("count",length(df['job'])).orderBy(length(df['job']).desc()).display()